[package]
name = "gmv_pjsip"
version = "0.1.0"
edition = "2021"

[features]
test-helpers = []

[dependencies]
#base = { git = "https://github.com/epimore/pigs.git",rev = "a0b9ed27",features = ["net"] }
base = { package = "base", path = "../pigs/base", features = ["net"] }

gmv_pjsip_sys = { path = "gmv_pjsip_sys" }
