use crate::dialog::InviteDialog;
use crate::error::{PjError, Result};
use crate::message::{ensure_name_addr, extract_uri_from_name_addr, SipMessage};
use crate::runtime::PjRuntime;
use crate::transport::{sent_by_from_addr, SipAssociation};

#[derive(Debug, Clone)]
pub struct ResponseOptions<'a> {
    pub code: u16,
    pub reason: &'a str,
    pub user_agent: &'a str,
    pub body: Option<&'a str>,
    pub content_type: Option<&'a str>,
    pub extra_headers: Vec<(&'a str, &'a str)>,
}

impl<'a> ResponseOptions<'a> {
    pub fn ok(user_agent: &'a str) -> Self {
        Self {
            code: 200,
            reason: "OK",
            user_agent,
            body: None,
            content_type: None,
            extra_headers: Vec::new(),
        }
    }
}

/// Build a SIP response by copying dialog/transaction defining headers from request.
///
/// The generated bytes are validated by PJSIP parser before returning, so Content-Length and SIP
/// syntax errors are caught early during development.
pub fn build_response(
    runtime: &PjRuntime,
    req: &SipMessage,
    opt: ResponseOptions<'_>,
) -> Result<Vec<u8>> {
    let body = opt.body.unwrap_or("");
    let mut out = String::with_capacity(512 + body.len());

    out.push_str(&format!("SIP/2.0 {} {}\r\n", opt.code, opt.reason));

    for via in req.header_values("Via") {
        out.push_str("Via: ");
        out.push_str(via);
        out.push_str("\r\n");
    }

    copy_header(&mut out, req, "From")?;
    copy_header(&mut out, req, "To")?;
    copy_header(&mut out, req, "Call-ID")?;
    copy_header(&mut out, req, "CSeq")?;

    out.push_str("User-Agent: ");
    out.push_str(opt.user_agent);
    out.push_str("\r\n");

    for (k, v) in opt.extra_headers {
        out.push_str(k);
        out.push_str(": ");
        out.push_str(v);
        out.push_str("\r\n");
    }

    if let Some(content_type) = opt.content_type {
        out.push_str("Content-Type: ");
        out.push_str(content_type);
        out.push_str("\r\n");
    }

    out.push_str(&format!("Content-Length: {}\r\n", body.as_bytes().len()));
    out.push_str("\r\n");
    out.push_str(body);

    let bytes = out.into_bytes();
    SipMessage::parse(runtime, &bytes)?;
    Ok(bytes)
}

fn copy_header(out: &mut String, req: &SipMessage, name: &'static str) -> Result<()> {
    let value = req.header_first(name).ok_or(PjError::MissingHeader(name))?;
    out.push_str(name);
    out.push_str(": ");
    out.push_str(value);
    out.push_str("\r\n");
    Ok(())
}

#[derive(Debug, Clone)]
pub struct RequestOptions<'a> {
    pub method: &'a str,
    pub request_uri: &'a str,
    pub association: &'a SipAssociation,
    pub from_uri: &'a str,
    pub from_tag: &'a str,
    pub to_uri: &'a str,
    pub to_tag: Option<&'a str>,
    pub call_id: &'a str,
    pub cseq: u32,
    pub contact_uri: &'a str,
    pub user_agent: &'a str,
    pub body: Option<&'a str>,
    pub content_type: Option<&'a str>,
    pub extra_headers: Vec<(&'a str, &'a str)>,
}

pub fn build_request(runtime: &PjRuntime, opt: RequestOptions<'_>) -> Result<Vec<u8>> {
    let body = opt.body.unwrap_or("");
    let branch = new_branch_token();
    let sent_by = sent_by_from_addr(opt.association.local_addr);

    let mut out = String::with_capacity(768 + body.len());
    out.push_str(&format!("{} {} SIP/2.0\r\n", opt.method, opt.request_uri));
    out.push_str(&format!(
        "Via: SIP/2.0/{} {};rport;branch={}\r\n",
        opt.association.transport.as_str(),
        sent_by,
        branch
    ));
    out.push_str(&format!(
        "From: {};tag={}\r\n",
        ensure_name_addr(opt.from_uri),
        opt.from_tag
    ));

    match opt.to_tag {
        Some(tag) if !tag.is_empty() => {
            out.push_str(&format!("To: {};tag={}\r\n", ensure_name_addr(opt.to_uri), tag));
        }
        _ => out.push_str(&format!("To: {}\r\n", ensure_name_addr(opt.to_uri))),
    }

    out.push_str(&format!("Call-ID: {}\r\n", opt.call_id));
    out.push_str(&format!("CSeq: {} {}\r\n", opt.cseq, opt.method));
    out.push_str(&format!("Contact: {}\r\n", ensure_name_addr(opt.contact_uri)));
    out.push_str("Max-Forwards: 70\r\n");
    out.push_str(&format!("User-Agent: {}\r\n", opt.user_agent));

    for (k, v) in opt.extra_headers {
        out.push_str(k);
        out.push_str(": ");
        out.push_str(v);
        out.push_str("\r\n");
    }

    if let Some(content_type) = opt.content_type {
        out.push_str("Content-Type: ");
        out.push_str(content_type);
        out.push_str("\r\n");
    }

    out.push_str(&format!("Content-Length: {}\r\n", body.as_bytes().len()));
    out.push_str("\r\n");
    out.push_str(body);

    let bytes = out.into_bytes();
    SipMessage::parse(runtime, &bytes)?;
    Ok(bytes)
}

pub fn build_ack_for_invite_2xx(
    runtime: &PjRuntime,
    dialog: &InviteDialog,
    user_agent: &str,
) -> Result<Vec<u8>> {
    let remote_tag = dialog
        .remote_tag
        .as_deref()
        .ok_or(PjError::MissingHeader("To tag"))?;

    let request_uri = dialog
        .remote_contact
        .as_deref()
        .and_then(extract_uri_from_name_addr)
        .unwrap_or(dialog.invite_request_uri.as_str());

    build_request(
        runtime,
        RequestOptions {
            method: "ACK",
            request_uri,
            association: &dialog.association,
            from_uri: &dialog.local_uri,
            from_tag: &dialog.local_tag,
            to_uri: &dialog.remote_uri,
            to_tag: Some(remote_tag),
            call_id: &dialog.call_id,
            cseq: dialog.invite_cseq,
            contact_uri: &dialog.local_contact,
            user_agent,
            body: None,
            content_type: None,
            extra_headers: Vec::new(),
        },
    )
}

pub fn new_branch_token() -> String {
    format!("z9hG4bK{}", new_token())
}

pub fn new_tag() -> String {
    new_token()
}

pub fn new_call_id(local_hint: &str) -> String {
    format!("{}@{}", new_token(), local_hint)
}

fn new_token() -> String {
    use std::hash::{Hash, Hasher};
    use std::time::{SystemTime, UNIX_EPOCH};

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let tid = std::thread::current().id();
    let mut h = std::collections::hash_map::DefaultHasher::new();
    now.hash(&mut h);
    format!("{:x}", h.finish() ^ format!("{:?}", tid).len() as u64)
}
